.PHONY: clean

championshiploderunner: championshiploderunner.o
	$(CC) -o championshiploderunner championshiploderunner.o

clean:
	$(RM) -rf championshiploderunner
	$(RM) -rf championshiploderunner.o
