.PHONY: clean

coco-high-score-enable: coco-high-score-enable.o
	$(CC) -o coco-high-score-enable coco-high-score-enable.o

clean:
	$(RM) -rf coco-high-score-enable
	$(RM) -rf coco-high-score-enable.o
